# Site settings
title: Hassan Adam Portfolio
baseurl: ""  # the subpath of your site, e.g. /blog
url: "http://adamh-Tech.github.io"  # the base hostname & protocol for your site
# Build settings
markdown: kramdown
theme: null  # When using remote_theme, set theme to null

# Remote Theme
remote_theme: pages-themes/hacker@v0.2.0

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
