title: Hassan Adam's  Portfolio
email: Hadam6424@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://adamh-Tech.github.io" # the base hostname & protocol for your site
github_username: adamh-Tech

# Build settings
markdown: kramdown
theme: minima # or any other theme you prefer
plugins:
  - jekyll-feed
