title: Hassan Adam's  Portfolio
email: Hadam6424@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://adamh-Tech.github.io" # the base hostname & protocol for your site
github_username: adamh-Tech

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman # changed theme to jekyll-theme-cayman
plugins:
  - jekyll-feed